'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=KINGTUBBY\SQLEXPRESS;Initial Catalog=CTPOS_B;Persist Security Info=Tr"& _ 
            "ue;User ID=ctposu;Password=ctposp")>  _
        Public ReadOnly Property ctPOS_bConnectionString() As String
            Get
                Return CType(Me("ctPOS_bConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=""D:\My Documents\Visual Studio 2005\"& _ 
            "Projects\CTPOS_F\ctmain_b.mdb""")>  _
        Public ReadOnly Property ctmain_bConnectionString() As String
            Get
                Return CType(Me("ctmain_bConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property lngStoreID() As Long
            Get
                Return CType(Me("lngStoreID"),Long)
            End Get
            Set
                Me("lngStoreID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property lngWSID() As Long
            Get
                Return CType(Me("lngWSID"),Long)
            End Get
            Set
                Me("lngWSID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.06")>  _
        Public Property dblTaxRate() As Double
            Get
                Return CType(Me("dblTaxRate"),Double)
            End Get
            Set
                Me("dblTaxRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MainPath() As String
            Get
                Return CType(Me("MainPath"),String)
            End Get
            Set
                Me("MainPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property POSPath() As String
            Get
                Return CType(Me("POSPath"),String)
            End Get
            Set
                Me("POSPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SQLServer() As String
            Get
                Return CType(Me("SQLServer"),String)
            End Get
            Set
                Me("SQLServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SQLDatabase() As String
            Get
                Return CType(Me("SQLDatabase"),String)
            End Get
            Set
                Me("SQLDatabase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ctuser")>  _
        Public Property SQLUserName() As String
            Get
                Return CType(Me("SQLUserName"),String)
            End Get
            Set
                Me("SQLUserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SQLPassword() As String
            Get
                Return CType(Me("SQLPassword"),String)
            End Get
            Set
                Me("SQLPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strDrawerPort() As String
            Get
                Return CType(Me("strDrawerPort"),String)
            End Get
            Set
                Me("strDrawerPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MS")>  _
        Public Property RcptPrinter() As String
            Get
                Return CType(Me("RcptPrinter"),String)
            End Get
            Set
                Me("RcptPrinter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Thank you for visiting our store!")>  _
        Public Property RcptFooter1() As String
            Get
                Return CType(Me("RcptFooter1"),String)
            End Get
            Set
                Me("RcptFooter1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Come Again!")>  _
        Public Property RcptFooter2() As String
            Get
                Return CType(Me("RcptFooter2"),String)
            End Get
            Set
                Me("RcptFooter2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Camp Wildwind Pines")>  _
        Public Property RcptHeader() As String
            Get
                Return CType(Me("RcptHeader"),String)
            End Get
            Set
                Me("RcptHeader") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property UseSQLServer() As Boolean
            Get
                Return CType(Me("UseSQLServer"),Boolean)
            End Get
            Set
                Me("UseSQLServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FirstSetup() As Boolean
            Get
                Return CType(Me("FirstSetup"),Boolean)
            End Get
            Set
                Me("FirstSetup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property blnUseDrawer() As Boolean
            Get
                Return CType(Me("blnUseDrawer"),Boolean)
            End Get
            Set
                Me("blnUseDrawer") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://donatelinq.net/smartpayments/transact.asmx")>  _
        Public ReadOnly Property CampTrakStore_net_donatelinq_SmartPayments() As String
            Get
                Return CType(Me("CampTrakStore_net_donatelinq_SmartPayments"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property lngLiveCharge() As Long
            Get
                Return CType(Me("lngLiveCharge"),Long)
            End Get
            Set
                Me("lngLiveCharge") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strXChargePath() As String
            Get
                Return CType(Me("strXChargePath"),String)
            End Get
            Set
                Me("strXChargePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LatitudeS")>  _
        Public Property strCashLinqUName() As String
            Get
                Return CType(Me("strCashLinqUName"),String)
            End Get
            Set
                Me("strCashLinqUName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5ITGJDnR")>  _
        Public Property strCashLinqPW() As String
            Get
                Return CType(Me("strCashLinqPW"),String)
            End Get
            Set
                Me("strCashLinqPW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property blnCamperSort() As Boolean
            Get
                Return CType(Me("blnCamperSort"),Boolean)
            End Get
            Set
                Me("blnCamperSort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property blnUseBell() As Boolean
            Get
                Return CType(Me("blnUseBell"),Boolean)
            End Get
            Set
                Me("blnUseBell") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnUsePrinter() As Boolean
            Get
                Return CType(Me("blnUsePrinter"),Boolean)
            End Get
            Set
                Me("blnUsePrinter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property intLinesBefore() As Integer
            Get
                Return CType(Me("intLinesBefore"),Integer)
            End Get
            Set
                Me("intLinesBefore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property intLinesAfter() As Integer
            Get
                Return CType(Me("intLinesAfter"),Integer)
            End Get
            Set
                Me("intLinesAfter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property blnOneCCReceipt() As Boolean
            Get
                Return CType(Me("blnOneCCReceipt"),Boolean)
            End Get
            Set
                Me("blnOneCCReceipt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1375")>  _
        Public Property strCraftID() As Long
            Get
                Return CType(Me("strCraftID"),Long)
            End Get
            Set
                Me("strCraftID") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TONY\SQLEXPRESS;Initial Catalog=ctpos_b;Persist Security Info=True;Us"& _ 
            "er ID=sa;Password=Varsity1")>  _
        Public ReadOnly Property ctpos_bConnectionString1() As String
            Get
                Return CType(Me("ctpos_bConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property blnUpdateSettings() As Boolean
            Get
                Return CType(Me("blnUpdateSettings"),Boolean)
            End Get
            Set
                Me("blnUpdateSettings") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CTPOS_F.My.MySettings
            Get
                Return Global.CTPOS_F.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
